import './globals.css'
import { Inter, Arimo } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const arimo = Arimo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arimo.className}>{children}</body>
    </html>
  )
}
